apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  root_password: c3VwZXJzZWN1cmVwYXNzd29yZA== #supersecurepassword
  user: azhzZ3Q= #k8sgt
  password: cGFzc3dvcmQ= #password
